package com.example.cardashboard.domain.model

/** Where a [VehicleState] came from. Surfaced in the UI so demo data is never mistaken for real. */
enum class VehicleDataSourceKind {
    /** Values generated by the built-in simulation. Not real vehicle data. */
    DEMO,

    /** Values read from a vehicle interface. */
    VEHICLE
}

/** Why no vehicle data is available. */
enum class VehicleDataUnavailableReason {
    /** This build has no supported vehicle interface on the current device. */
    NO_SUPPORTED_INTERFACE,

    /** An interface exists but is not connected right now. */
    NOT_CONNECTED,

    /** The source is connected but failed while reading. Usually transient. */
    READ_FAILED
}

/** Everything the dashboard can be told about vehicle data at a given moment. */
sealed interface VehicleDataState {

    /** No snapshot has arrived yet. */
    data object Loading : VehicleDataState

    /** A usable, already sanitized snapshot. */
    data class Available(
        val vehicleState: VehicleState,
        val source: VehicleDataSourceKind
    ) : VehicleDataState

    /**
     * No usable data. [lastKnownState] lets the UI keep the last good reading on screen, greyed
     * out, instead of blanking the cluster during a brief dropout.
     */
    data class Unavailable(
        val reason: VehicleDataUnavailableReason,
        val lastKnownState: VehicleState? = null
    ) : VehicleDataState
}
